#!/bin/bash

random_string=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 3)

google-chrome --new-window http://localhost:3001/test/create?name=bob_${random_string}&
google-chrome --new-window --incognito http://localhost:3001/test/create?name=tom_${random_string}&

